# # Right-only overrides (peripheral). Keep empty if all settings are shared in yk_do52pro.conf.
# CONFIG_ZMK_USB=n
# CONFIG_UART_INTERRUPT_DRIVEN=y

CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ESB=y
CONFIG_ZMK_SPLIT_BLE=n
CONFIG_ZMK_SPLIT_WIRED=n
CONFIG_ZMK_BLE=n