#the ps2 driver in zephyr does not support the resend callback, so we need to enable it in the ps2 driver in order to use it in the ps2 mouse driver. 
#CONFIG_PS2_UART_ENABLE_PS2_RESEND_CALLBACK=y
CONFIG_ZMK_INPUT_MOUSE_PS2_ENABLE_ERROR_MITIGATION=y

CONFIG_SERIAL=y
CONFIG_UART_ASYNC_API=y
CONFIG_UART_INTERRUPT_DRIVEN=y
#CONFIG_PM_DEVICE=n